### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by leileilin** [THUNLP-MT/SelfSupervisedQE#1]
你好，能不能提供数据集下载的脚本？
非常感谢！！！

**Comment by ZYH111** [comment]
您好！我更新了数据集下载的脚本。注意实验中用的数据集不能全自动下载，有一些数据集必须手动下载（具体情况在我提供的脚本中有说明）。

**Comment by leileilin** [comment]
> 您好！我更新了数据集下载的脚本。注意实验中用的数据集不能全自动下载，有一些数据集必须手动下载（具体情况在我提供的脚本中有说明）。

好的，非常感谢！
