### ISSUE TITLE
Why every 2nd label was selected instead of every label in evaluate.py?

### ISSUE THREAD

**Issue by kaleemiqb** [THUNLP-MT/SelfSupervisedQE#4]
Hi. In **evaluate.py** inside **make_word_outputs_final** function, it is reading word level labels for threshold tuning:
```
flabels = open(threshold_tune, 'r')
        labels = [x.strip().split(' ')[1 : : 2] for x in flabels]
```
1) Here it is reading **every alternate label starting from 2nd label onwards  [1: :2] and not every single label.** What's the reason behind not reading every single label in the dev.tags file and also starting from 2nd label onwards?

2) Take en-de data for example. The number of OK/BAD tags in the dev.tags file do not match the number of words in the german sentence. E.g a german sentence might have 5 words but number of OK/BAD tags in word tags file is much more e.g 10 tags. It is even more than if we tokenize the sentence into subwords tokens. How exactly was the OK/BAD data prepared? If I have source, target pairs, how should I proceed to prepate this OK/BAD labels data. Should **each label be done for each "word"** in the target sentence? or Should it be **each label for each "sub word"** obtained from say BERT tokenizer. In the en-de data, these labels are much more than either the number of words or subwords in the target sentence so I am not sure how they were obtained. Please guide. Thanks.

**Comment by ZYH111** [comment]
This is because the OK/BAD tags in the file dev.tags contains two types of tags: (1) tags for words and (2) tags for gaps. These tags appears alternately in each row. In this work, we focus on the tags for words and ignore the tags for gaps. Therefore, we use every alternate label starting from 2nd label onwards [1: :2].

**Comment by kaleemiqb** [comment]
Oh so those extra ones are for the gaps. That explains it! Thank you for the response.
